language: java

sudo: false

jdk:
  - oraclejdk8

install: false

env:
  global:
    - TERM=dumb
  matrix:
    PROFILE=development

script:
  - SPRING_PROFILES_ACTIVE=${PROFILE} ./gradlew clean build

notifications:
  email: false
