language: java

sudo: false

jdk:
  - oraclejdk8

install: false

env:
  global:
    - TERM=dumb
  matrix:
    PROFILE=development

script:
  - ./gradlew clean build -Dspring.profiles.active=${PROFILE}

notifications:
  email: false
